### ISSUE TITLE
broken link to I-D.ietf-ace-oauth-authz

### ISSUE THREAD

**Issue by anthonykirby** [nominetresearch/ietf-mqtt-ace-profile#13]
shouldn't link back to this document
try replacing with "Section 4 of [I-D.ietf-ace-oauth-authz]"

**Comment by ciseng** [comment]
Using this gives an error: 
<xref target="RFC5226" x:fmt="of" x:sec="4.1"/>
Not sure what to add in to make it work. We use the rfc2629 - so it should work in theory.

**Comment by anthonykirby** [comment]
I can't reproduce a problem: seems OK on https://tools.ietf.org/html/draft-sengul-ace-mqtt-tls-profile-02 & it's fine when I render it with xml2rfc.

**Comment by anthonykirby** [comment]
I tried to get this to work:  at least the xml2rfc that I have doesn't understand the `x:` namespace.

Plausible documentation at https://greenbytes.de/tech/webdav/rfc2629xslt/rfc2629xslt.html#extensions

I tried adding `xmlns:x="http://purl.org/net/xml2rfc/ext"` to the `<rfc ...>` element (which would be a plausible requirement in xml land) but that didn't help.

**Comment by ciseng** [comment]
We do not know how to fix this yet.

**Comment by ciseng** [comment]
Was not relevant to us. Will ignore.
