### ISSUE TITLE
clarify password field in MQTT connect (section 2.1.2)

### ISSUE THREAD

**Issue by anthonykirby** [nominetresearch/ietf-mqtt-ace-profile#19]
"The Password field MUST be set to the keyed message digest (MAC) or 
signature."

Please make it explicit already here that this is the 
Proof-of-possession mechanism for the key associated to the token.

**Comment by ciseng** [comment]
This is fixed. Password field description has been updated. It also clarified it contains the Key for the PoP mechanism.
