### ISSUE TITLE
refine "scope strings" paragraph (section 2.1.3 token validation)

### ISSUE THREAD

**Issue by anthonykirby** [nominetresearch/ietf-mqtt-ace-profile#24]
"Note: Scope strings MAY follow ..."

Note that a scope is a "space-delimited list strings" (OAuth 2.0 3.3.)
so you could include several topics in one scope as in e.g. "connect 
publish_topic1 publish_topic2 subsrcibe_topic3"

The use of 'aud' as described in this paragraph is definitely not the 
intended use, and I would not recommend this type of use. See 
https://tools.ietf.org/html/rfc7519#section-4.1.3 for the definition of aud.

**Comment by ciseng** [comment]
So we can just remove the note, and accept aud=RS, scope="publish_topic1 subscribe_topic2 etc." which is fine by me.
