### ISSUE TITLE
clarify that token expiration check doesn't imply full validation (section 2.4 "Token Expiration")

### ISSUE THREAD

**Issue by anthonykirby** [nominetresearch/ietf-mqtt-ace-profile#25]
"The token validation is done either by checking the 'exp' claim of a
    CWT/JWT or via performing an introspection request with the
    Authorization server as described in Section 8.2 of the ACE framework
    [I-D.ietf-ace-oauth-authz]."

The word "token validation" here could be misconstrued to ignoring 
crypto wrappers, token issuers ect. While it is clear from the context 
(to me) that you only refer to checking the expiration of a token, the 
full validation of a token would include the following steps:

1. Check that the issuer of the token (= AS) is acceptable
2. Check the cryptographic wrapper of the token (may be MAC or signature or
AEAD encryption)
3. Check that the token contains all expected claims
4. Check that the "exp" and "nbf" claims are fulfilled if present
5. Check that the "aud" claim applies to the recipient if present

**Comment by ciseng** [comment]
Fixed the easy part. The steps mentioned by Ludwig can be explicitly added to the token validation section. We have not done so because we were thinking to be more flexible with the token fields. Let's not be so and converge to a single token/scope representation. Then, we can shape up this section.

**Comment by ciseng** [comment]
Will check this after the pull request is merged.

**Comment by ciseng** [comment]
Checked added some text to address this at 2.1.3.

**Comment by ciseng** [comment]
This is done.
