### ISSUE TITLE
define encoding for MAC/signature used by MQTT5 "Auth" + example (section 3.1)

### ISSUE THREAD

**Issue by anthonykirby** [nominetresearch/ietf-mqtt-ace-profile#26]
"The first option is that Authentication data contains both the token
    and the keyed message digest (MAC) or signature as described in
    Section 2.1.2."

You need to specify how these two items are encoded. I would suggest a
CBOR array since this property expects binary data. An example would also
be very helpful here.

**Comment by ciseng** [comment]
Actually Ludwig is referring to classical method. So we have to make the change in 2.1.2 - we have not made any assumption how the token could be encoded CBOR (CWT) or JSON (JWT). I am not sure CBOR is a MUST. It may be a SHOULD.  The example, which Ludwig already asked, also belongs to 2.1.2.
