### ISSUE TITLE
define format for response to AS-discovery CONNECT (section 3.1)

### ISSUE THREAD

**Issue by anthonykirby** [nominetresearch/ietf-mqtt-ace-profile#27]
[at the end of section 3.1]
"... RS responds with a CONNACK reason code '0x87 (Not Authorized)' and
    includes a User Property set to the address of the AS."

You need to specify the format of this user property, in order to mirror
the framework's section 5.1.2. I guess you could use either a JSON map
or binary data containing a CBOR map for this.

**Comment by ciseng** [comment]
Not sure whether to mention base 64 encoding as the user property field is UTF-8.
